### ISSUE TITLE
Multiple Spaces share entered widget

### ISSUE THREAD

**Issue by ArchBlood** [GreenMeteor/premium-modules#1]
A weird issue where two or more spaces having the module enabled share the same widget link

**Comment by ArchBlood** [comment]
@luke- I'm not really sure on what we did wrong here, would be amazing for some insight into a quick fix for this

**Comment by luke-** [comment]
Which module?

**Comment by ArchBlood** [comment]
> Which module?

Premium Discord, somehow instead of allowing individual spaces a setting to create their own widget separate from other spaces we ended up allowing all spaces to share the same widget when the module is enabled

**Comment by luke-** [comment]
As quick 


https://github.com/GreenMeteor/humhub-premium_discord-module/blob/master/controllers/SpaceAdminController.php#L15
```
$model = new SpaceForm(['contentContainer' => $this->contentContainer]);
```

**https://github.com/GreenMeteor/humhub-premium_discord-module/blob/master/models/SpaceForm.php**

make sure to always get/set the settings for the content container (space) 

e.g.

Replace

```$module->settings``` or ``` Yii::$app->getModule('premium_discord')->settings```  with ```$this->getSettings()```

**Comment by ArchBlood** [comment]
> **https://github.com/GreenMeteor/humhub-premium_discord-module/blob/master/models/SpaceForm.php**
> 
> make sure to always get/set the settings for the content container (space)
> 
> e.g.
> 
> Replace
> 
> `$module->settings` or ` Yii::$app->getModule('premium_discord')->settings` with `$this->getSettings()`

Could I get an example for this? Using `$this->getSettings()` just throws an error

Using anything other than the code used now throws errors :frowning_face:

**Comment by luke-** [comment]
Can you give me more info about the error?

**Comment by ArchBlood** [comment]
When I try using `$this-getSettings()` it throws an error that SpaceForm::module can't be used from

```php
    /**
     * @return SettingsManager
     */
    private function getSettings()
    {
        return $this->module->settings->contentContainer($this->contentContainer);
    }
```

**Comment by luke-** [comment]
Try replace $this->module with Yii::$app->getModule('premium_discord')

**Comment by ArchBlood** [comment]
That fixed that, now on loadSettings() & save() the value isn't loaded correctly or not at all :thinking:

**Comment by ArchBlood** [comment]
I kind of feel silly after looking over the code for `getSUrl()`, thanks for the quick walkthrough @luke- this really helped! :sweat_smile:
