### ISSUE TITLE
Discussions Module

### ISSUE THREAD

**Issue by wehowski** [GreenMeteor/premium-modules#3]
Hello,
there where bugs reported in the discussions module.
- A user reported that she cannot create postings, unfortunatly I could not reproduce this by myself and coud create postings.
- As admin and as autor I cannot delete postings
- Since today (I do not know changes?) I cannot open the module: "You take the wrong route". This affects the index route, the view details view is visible.

If it helps and needed I can give a link and/or access.

regards,
Till

**Comment by wehowski** [comment]
`
Since today (I do not know changes?) I cannot open the module: "You take the wrong route". This affects the index route, the view details view is visible.
`
ALthough I am not sure about the reason I can say, before the route was gone (it was working a day before) I created an additional link in the top menu via own pages, later deleted that link. Now the index shows "wrong route".

**Comment by wehowski** [comment]
This issue could be closed, **an additional report will be added at the end of this comment**.
My solution for problem 2 and 3 was: (Problem 1 could not be reproduced but look additional report)
I deactivated, deinstalled and re-installed the module. That helped.

**Additional report:**
Posting and deleting is possible now and the index view works, but the author-IDs missmatch at the first view test-posts (author A can post as author B).
This I guess is the reason  because just the Module-Data from the first installation was not removed correctly/completly and interferes with the data for the second installation?
So maybe it could help to get the installation removed completly with data to do a fresh install?

**Comment by ArchBlood** [comment]
Alright, so here's the breakdown of what we've found;
- `delete()` is no longer supported we're now using `hardDelete()` to fix this issue;
- I've not seen any issues with creating/updating discussions;
- We've switched `public $deleteAccess = [ManageUsers::class];` so that it now uses `ManageContent::class`, small note, doing this doesn't allow anyone other than the discussion creator to delete their discussions, if this isn't liked you can always use the other method again by editing the `$deleteAccess = []`, we may implement a way of toggling this later.
- We've noticed some other bugs when it comes to using the User profile image, so we've temperarily removed this
- Due to the Verified module being in the marketplace now we've removed this from the Discussions module, we also have plans on implementing an interface method so that it can be used again.

I'll work on uploading v1.0.0-beta.3 as soon as I can, you'll be able to download it from the marketplace as soon as it's uploaded, note that it has to be reviewed by HumHub's review team before it officially hits the marketplace and is viewable from your HumHub instance marketplace backend.

### Tested HumHub Versions
- [x] HumHub v1.15
- [x] HumHub v1.14.x

**Comment by wehowski** [comment]
Hello @ArchBlood,
I have updated to the latest version of humhub.
I am not sure where to find the current version? In protected/humhub/config/common.php it is 
 'version' => '1.15.0',
The PHP is 8.2.13
MariaDB is 10.3.39

**Thank you!**

**Comment by ArchBlood** [comment]
> Hello @ArchBlood, I have updated to the latest version of humhub. I am not sure where to find the current version? In protected/humhub/config/common.php it is 'version' => '1.15.0', The PHP is 8.2.13 MariaDB is 10.3.39
> 
> **Thank you!**

You can get the new version here, just enter your License Key to verify that you've paid for the module;
https://marketplace.humhub.com/downloads/enter-licence/discussions-v1.0.0-beta.3

**Comment by wehowski** [comment]
Everything works except I cannot comment on posts: I do not see the "comment" link, the comment form disappeared. 

JS console says:
[Violation]Added non-passive event listener to a scroll-blocking <ein> Ereignis. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
humhub-bundle.js?v=1699291208:1 [Violation]Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952:
      p.haseventlistener ? (this._bind = function(e, t, r, n) {
            d.events.push({
                e: e,
                n: t,
                f: r,
                b: n,
                q: !1
            }),
            e.addEventListener(t, r, n || !1)
        }

**Comment by ArchBlood** [comment]
> Everything works except I cannot comment on posts: I do not see the "comment" link, the comment form disappeared.
> 
> JS console says: [Violation]Added non-passive event listener to a scroll-blocking Ereignis. Consider marking event handler as 'passive' to make the page more responsive. See humhub-bundle.js?v=1699291208:1 [Violation]Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952: p.haseventlistener ? (this._bind = function(e, t, r, n) { d.events.push({ e: e, n: t, f: r, b: n, q: !1 }), e.addEventListener(t, r, n || !1) }

That's strange, I'm able to view and comment on posts. 🤔
![Screenshot_8](https://github.com/GreenMeteor/premium-modules/assets/35392110/d419c401-4bff-4f6c-9a75-70f3422f79d8)
![Screenshot_9](https://github.com/GreenMeteor/premium-modules/assets/35392110/3a552db8-8666-41dc-aa6d-720837ba74d5)

I see the console errors, but this doesn't seem to be an issue really. 🤔

In your `_view.php` file line 26 and remove `onclick="location.href = '<?= Url::to(['/discussions/view', 'id' => $model->id])?>'"` then this will disappear.

**Comment by ArchBlood** [comment]
I've updated the uploaded package to include this fix, although I'm not exactly sure on why it would throw this error, as it's never done this before. 🤔

**Comment by ArchBlood** [comment]
> I uploaded the fixed package and did another testposting and can comment now. **Everything is working now, I cannot reproduce any error anymore!**

So I can assume that this issue can be closed now?

**Comment by wehowski** [comment]
Yes. Thank you!!!
