### ISSUE TITLE
Cannot delete postings [Discussion Board Module]

### ISSUE THREAD

**Issue by wehowski** [GreenMeteor/premium-modules#5]
Hi,
I installed the last two updates. Now I have the following issue:

- Admins and Authors cannot delete postings

Sorry, I cannot reproduce any error messages so far in the protocolls, error_log is empty, after clicking the delete-icon, the page reloads but the posting still exists.

'Humhub version' => '1.16.1',
The PHP is 8.3.8
MariaDB is 10.3.39

**Comment by ArchBlood** [comment]
This is probably due to the switch of permissions from `ManageContent` to `ManageUsers`, this is needed due to issues that were reported with the `ManageContent` permissions, so now to be able to manage actions in the Discussions module you must have permissions to manage users.

**Comment by ArchBlood** [comment]
If it's needed in your community it's recommended to switch `use humhub\modules\admin\permissions\ManageUsers;` with `use humhub\modules\content\permissions\ManageContent;` and `public $deleteAccess = [ManageUsers::class];` with `public $deleteAccess = [ManageContent::class];`

**Comment by wehowski** [comment]
I changed $deleteAccess to humhub\modules\content\permissions\ManageContent now.
The problem still exists. Although I can delete answers to postings I cannot delete the opening posting/the thread.

**Comment by ArchBlood** [comment]
> I changed $deleteAccess to humhub\modules\content\permissions\ManageContent now. The problem still exists. Although I can delete answers to postings I cannot delete the opening posting/the thread.

I'm still not able to reproduce the issue on my end with either permission set. I'd need more information, if possible could you provide a testing account?

**Comment by wehowski** [comment]
Hello,
I created a testuser and send the password to your email: kodo@greenmeteor.net

**Comment by ArchBlood** [comment]
> Hello, I created a testuser and send the password to your email: [kodo@greenmeteor.net](mailto:kodo@greenmeteor.net)

Once I'm able to I'll jump on and take a look.

**Comment by ArchBlood** [comment]
I'm not seeing any issues on my end

### Test Post
![Screenshot_1](https://github.com/GreenMeteor/premium-modules/assets/35392110/07f6d8c7-ad8b-4db7-bc9c-70094683ec9d)

### Other Test Post
![Screenshot_2](https://github.com/GreenMeteor/premium-modules/assets/35392110/85fff660-4871-4908-965e-622397de0200)

The reason why we made the switch is because there are no group permissions for ManageContent class as shown in the attached screenshot below;
![Screenshot_3](https://github.com/GreenMeteor/premium-modules/assets/35392110/3b839228-be08-4630-a1b8-1c03dafe3796)

If @luke- were to make this possible then I'd be more inclined to reintroduce the use of the ManageContent permission.

**Comment by ArchBlood** [comment]
In the future GreenMeteor/discussions/pull/17 (i.e. `ManageDiscussions`) will replace both `ManageUsers` & `ManageContent` permissions.

**Comment by wehowski** [comment]
Ok, thank you for testing, please excuse my late response.

Did you test to CLICK the delete button on the Test Post? If so, please ignore my answer.
I still cannot delete the initial opening posting of a disscussion board thread.

However, as it is still BETA, I can wait for next version.

**Comment by ArchBlood** [comment]
> Ok, thank you for testing, please excuse my late response.
> 
> Did you test to CLICK the delete button on the Test Post? If so, please ignore my answer.
> I still cannot delete the initial opening posting of a disscussion board thread.
> 
> However, as it is still BETA, I can wait for next version.

I'll have to look into the delete issue.

**Comment by ArchBlood** [comment]
Beta 7 has been pushed with the new permissions and we also completely replaced the broken delete function, currently by default administrators are allowed to edit and delete discussions, to allow other user groups to also do the same thing you must change the Manage Discussions permission within the user group's permissions area.

**Comment by wehowski** [comment]
I just installed beta.7 and no CAN delete the postings without any error.

Thank you!!!

[can be closed]
