### ISSUE TITLE
reduce size top button on mobile version

### ISSUE THREAD

**Issue by ilMagnifico** [GreenMeteor/premium-modules#7]
reduce size top button on mobile version so that it doesn't get too near the "send" button on post/comment.
![Screenshot_20241101_114253](https://github.com/user-attachments/assets/4d0ee07c-3c48-4b99-8056-954f5bc97fbb)

**Comment by ArchBlood** [comment]
Resizing will not work in this case as the scroll up module is appended to `.layout-content-container`, we recommend using the Scroll Up module's configuration (i.e. `/scrollup/admin/index`) to change the position to right or left.

**Comment by ilMagnifico** [comment]
> Resizing will not work in this case as the scroll up module is appended to `.layout-content-container`, we recommend using the Scroll Up module's configuration (i.e. `/scrollup/admin/index`) to change the position to right or left.
Could you please specify what do I have to do? Thx

**Comment by ArchBlood** [comment]
> > > Resizing will not work in this case as the scroll up module is appended to `.layout-content-container`, we recommend using the Scroll Up module's configuration (i.e. `/scrollup/admin/index`) to change the position to right or left.
> >>
> > Could you please specify what do I have to do? Thx

To be more specific, use the Scroll Up's configurations.
![Screenshot_4](https://github.com/user-attachments/assets/65fe10ed-3ad0-411d-ae22-47962e98e37b)
![Screenshot_5](https://github.com/user-attachments/assets/a653775f-2111-4eb4-b5ca-604ddc398dc1)
![Screenshot_6](https://github.com/user-attachments/assets/ff2b1ba0-d2df-438a-882b-26c3cbc3b1c1)

**Comment by ilMagnifico** [comment]
Thank you.

**Comment by ArchBlood** [comment]
If no other help is needed this issue can be closed.
